### ISSUE TITLE
Some records are not carried over

### ISSUE THREAD

**Issue by saberthesword** [OddDrifter/leveledlistresolver#1]
Hi, I noticed that when looking in xEdit, the records from Cutting Room Floor do not get carried over
![image](https://user-images.githubusercontent.com/61779318/114751673-05010c80-9d88-11eb-9c0b-770ae6b177cf.png)

**Comment by OddDrifter** [comment]
What mod is "sm_arcanespellsastaves.esp" from? Also, Synthesis should make a log file when you run the patcher. Could you post that too?

**Comment by saberthesword** [comment]
https://www.nexusmods.com/skyrimspecialedition/mods/12793

[log-20210415.txt](https://github.com/OddDrifter/leveledlistresolver/files/6312672/log-20210415.txt)

**Comment by OddDrifter** [comment]
Does the same thing happen if you run Synthesis without StaffGenerator?

**Comment by OddDrifter** [comment]
The issue with staves should be fixed now.
