### ISSUE TITLE
Hangs on certain leveled lists

### ISSUE THREAD

**Issue by mdfairch** [OddDrifter/leveledlistresolver#13]
The line from RecordPatcher.LeveledItem.cs:
`var intersection = (lowest.Entries ?? Array.Empty<ILeveledNpcEntryGetter>()).IntersectWith(extentContexts[1..].Aggregate(extentContexts[0].Record.Entries ?? Enumerable.Empty<ILeveledNpcEntryGetter>(), (i, k) => i.IntersectWith(k.Record.Entries)));`
seems to get stuck in a recursive loop LItemBook3All. I've checked in xedit for cyclic leveled lists (and tried manually resolving that list ahead of time). In test where I let the patcher run for fiveminutes with a Console.WriteLine message in the IntersectWith function, there were 4300 calls to IntersectWith just for LItemBook3All.

Sorry I can't provide more information, but my C# experience is pretty limited so it's difficult to get much debugging information.

**Comment by OddDrifter** [comment]
What mods do you have the affect `LItemBook3All`?

**Comment by mdfairch** [comment]
Books Book Books and Beyond Reach (and their LotD patches).

**Comment by mdfairch** [comment]
This is just a wild guess based on the sheer number of calls ... but is IntersectWith getting called in proportion to the size of the leveled list raised to power of the number of times the list is overwritten?

**Comment by OddDrifter** [comment]
At most, it should only be called `(number of overrides - 1)` times.

**Comment by mdfairch** [comment]
Any chance you can make the older version available? The lack of other reports suggests this problem may be unique to my load order, but until I figure out the conflict it would be nice to have the version that works with it.

**Comment by OddDrifter** [comment]
If you're using this through the Synthesis GUI, you can use the Commit option to revert to 89808df55088b283697032cbeb33a2c78decc5c8 or you can specify [1.5.X](https://github.com/OddDrifter/leveledlistresolver/tree/1.5.X) as the Branch.


![Screenshot 2023-07-29 135515](https://github.com/OddDrifter/leveledlistresolver/assets/65688322/5d2a62e6-9b2b-4a93-a077-6e7ad6a13771)

**Comment by mdfairch** [comment]
Perfect! Thanks for the very clear explanation; I'm not a coder so I miss some of the details of using github well.
