### ISSUE TITLE
Selectable categories

### ISSUE THREAD

**Issue by eleroy5** [OddDrifter/leveledlistresolver#7]
First time i use this solver for a new playthrought I thought it was a holy mod.
After a few days i encounter many problems in my playthrought. Not only by this mod but also with synthesis item weight and synthesis SynBookSmart and Synthesis DisplaySpellTome Level.

For leveledlist resolver i thought only items like armors and weapons were impacted.

But in fact it impacts too the following categories:
BOOK : It's a problem because it could overwrites localized names and descriptions and weight. (Note that Synthesis ItemWeight does the same except for weight as it's its job).
ENCOUNTER ZONES: Could replace some others synthesis solution if there were settings but in this case it overwrites others synthesis for encounter zones with settings.
MAGIC EFFECTS: Why ? Maybe you have reasons i have not notice. But most people use magic mods, Odin, Ordinator, Apocalypse or many others. This category is very annoying for all people who use them
NPC: Idem. Most people have at least one mod which modifies one or more NPC. There are tons. LeveledList resolver don't take them into accounts. I tried to overwrites LeveledList by my mods with NPC but sometimes i can't load them after so i must enter xEdit and manually overwrites all npc data. For example i have BeardsOfPower-SonsOf Skyrim. LeveledList resolver backward all appearances changes to skyrim original.
And so on for PERK and RACE. There is specific mods for that.

As a user of this solution and i like it but it could be an improvement to:
-at least have a setting to choose wich categories to be impacted by the resolver.
-In a second time a setting for customize certain categories.

With options like that could be a masterpiece! In my opinion.

**Comment by OddDrifter** [comment]
If you use any other synthesis patchers, you should probably take a look at what they might be doing. This one only affects leveled lists.
