### ISSUE TITLE
Not an Issue: How exactly would this work better than a Bashed Patch for Levelled lists?

### ISSUE THREAD

**Issue by ghyujkilop** [OddDrifter/leveledlistresolver#9]
For instance, would the need for an extra esp like this be useless because it's primarily using bash tags?
![image](https://user-images.githubusercontent.com/70988876/158353848-a9984d03-f752-4144-a674-ebea68f3c319.png)

**Comment by OddDrifter** [comment]
Besides not needing to use bash tags to detect leveled list conflicts, this isn't really any better than just making a bashed patch. I know from experience that the leveled list fix from WACCF isn't necessary with this, but I can't guarantee that will be the case with any other patches.
